### ISSUE TITLE
Qual ERP foco do Projeto?

### ISSUE THREAD

**Issue by matbrgz** [erpbrasil/erpbrasil.transmissao#3]
Para qual ERP essas implementações são? Odoo ou ERPNext?

**Comment by mileo** [comment]
Elas estão feitas em cima do Odoo, mas você pode usa-las no ERPnext sem problemas.

Continuaremos colocando novas funcionalidades ao longo do tempo para suportar outros projetos.

E estaremos a disposição para efetuar qualquer coisa que possamos fazer para facilitar a integração com outros sistemas.

Você pode me encontrar no telegram:

https://t.me/luisfelipemileo

Ou no grupo do Odoo do telegram.

https://t.me/odoobrazil
